name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test printing gpg version
      run: gpg --version
    - name: Decrypt large secret
      run: ./scripts/decrypt_google_services.sh
      env:
        FIREBASE_SECRET_PASSPHRASE: $
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
